# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LiveExportLogSender/messagebus.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LiveExportLogSender/messagebus.proto',
  package='MessageBus',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n$LiveExportLogSender/messagebus.proto\x12\nMessageBus\"b\n\x07LogData\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12#\n\x05level\x18\x02 \x01(\x0e\x32\x14.MessageBus.LogLevel\x12\x0e\n\x06sender\x18\x03 \x01(\t\x12\x0f\n\x07message\x18\x04 \x01(\t\"\xb9\x02\n\x0fPresenceMessage\x12*\n\x06status\x18\x01 \x01(\x0e\x32\x1a.MessageBus.PresenceStatus\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x03 \x01(\t\x12\x15\n\rserial_number\x18\x04 \x01(\t\x12\x16\n\x0e\x64\x65vice_version\x18\x06 \x01(\t\x12\x16\n\x0e\x64\x65vice_session\x18\x07 \x01(\t\x12\x16\n\x0e\x64\x65vice_channel\x18\x08 \x01(\t\x12\x1a\n\x12published_channels\x18\t \x03(\t\x12\x1b\n\x13subscribed_channels\x18\n \x03(\t\x12\x1b\n\x13heartbeat_frequency\x18\x0b \x01(\r\x12\x1b\n\x13heartbeat_threshold\x18\x0c \x01(\r*\x1f\n\x07Version\x12\t\n\x05\x64ummy\x10\x00\x12\t\n\x05value\x10\x02*7\n\x08LogLevel\x12\t\n\x05\x65rror\x10\x00\x12\x0b\n\x07warning\x10\x01\x12\x08\n\x04info\x10\x02\x12\t\n\x05\x64\x65\x62ug\x10\x03*F\n\x0ePresenceStatus\x12\t\n\x05\x45rror\x10\x00\x12\x10\n\x0cInitializing\x10\x01\x12\t\n\x05Ready\x10\x02\x12\x0c\n\x08Updating\x10\x03\x62\x06proto3'
)

_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='MessageBus.Version',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='dummy', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='value', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=468,
  serialized_end=499,
)
_sym_db.RegisterEnumDescriptor(_VERSION)

Version = enum_type_wrapper.EnumTypeWrapper(_VERSION)
_LOGLEVEL = _descriptor.EnumDescriptor(
  name='LogLevel',
  full_name='MessageBus.LogLevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='error', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='warning', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='info', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='debug', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=501,
  serialized_end=556,
)
_sym_db.RegisterEnumDescriptor(_LOGLEVEL)

LogLevel = enum_type_wrapper.EnumTypeWrapper(_LOGLEVEL)
_PRESENCESTATUS = _descriptor.EnumDescriptor(
  name='PresenceStatus',
  full_name='MessageBus.PresenceStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Error', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Initializing', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Ready', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Updating', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=558,
  serialized_end=628,
)
_sym_db.RegisterEnumDescriptor(_PRESENCESTATUS)

PresenceStatus = enum_type_wrapper.EnumTypeWrapper(_PRESENCESTATUS)
dummy = 0
value = 2
error = 0
warning = 1
info = 2
debug = 3
Error = 0
Initializing = 1
Ready = 2
Updating = 3



_LOGDATA = _descriptor.Descriptor(
  name='LogData',
  full_name='MessageBus.LogData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='MessageBus.LogData.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='level', full_name='MessageBus.LogData.level', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sender', full_name='MessageBus.LogData.sender', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='MessageBus.LogData.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=150,
)


_PRESENCEMESSAGE = _descriptor.Descriptor(
  name='PresenceMessage',
  full_name='MessageBus.PresenceMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='MessageBus.PresenceMessage.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='MessageBus.PresenceMessage.device_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='MessageBus.PresenceMessage.device_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serial_number', full_name='MessageBus.PresenceMessage.serial_number', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_version', full_name='MessageBus.PresenceMessage.device_version', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_session', full_name='MessageBus.PresenceMessage.device_session', index=5,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_channel', full_name='MessageBus.PresenceMessage.device_channel', index=6,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='published_channels', full_name='MessageBus.PresenceMessage.published_channels', index=7,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subscribed_channels', full_name='MessageBus.PresenceMessage.subscribed_channels', index=8,
      number=10, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeat_frequency', full_name='MessageBus.PresenceMessage.heartbeat_frequency', index=9,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heartbeat_threshold', full_name='MessageBus.PresenceMessage.heartbeat_threshold', index=10,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=153,
  serialized_end=466,
)

_LOGDATA.fields_by_name['level'].enum_type = _LOGLEVEL
_PRESENCEMESSAGE.fields_by_name['status'].enum_type = _PRESENCESTATUS
DESCRIPTOR.message_types_by_name['LogData'] = _LOGDATA
DESCRIPTOR.message_types_by_name['PresenceMessage'] = _PRESENCEMESSAGE
DESCRIPTOR.enum_types_by_name['Version'] = _VERSION
DESCRIPTOR.enum_types_by_name['LogLevel'] = _LOGLEVEL
DESCRIPTOR.enum_types_by_name['PresenceStatus'] = _PRESENCESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogData = _reflection.GeneratedProtocolMessageType('LogData', (_message.Message,), {
  'DESCRIPTOR' : _LOGDATA,
  '__module__' : 'LiveExportLogSender.messagebus_pb2'
  # @@protoc_insertion_point(class_scope:MessageBus.LogData)
  })
_sym_db.RegisterMessage(LogData)

PresenceMessage = _reflection.GeneratedProtocolMessageType('PresenceMessage', (_message.Message,), {
  'DESCRIPTOR' : _PRESENCEMESSAGE,
  '__module__' : 'LiveExportLogSender.messagebus_pb2'
  # @@protoc_insertion_point(class_scope:MessageBus.PresenceMessage)
  })
_sym_db.RegisterMessage(PresenceMessage)


# @@protoc_insertion_point(module_scope)
